name: Convert Markdown to PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Pandoc
      run: sudo apt-get install -y pandoc

    - name: Install LaTeX
      run: sudo apt-get install -y texlive-full

    - name: Combine Markdown files
      run: cat $(find . -name "*.md" | sort) > combined.md

    - name: Convert to PDF
      run: pandoc combined.md -o output.pdf

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v3
      with:
        name: output-pdf
        path: output.pdf
